name: Docker-Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:

  build:


    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag yuvalost/final-python:${{ github.run_number }}
    - name: Log in to Docker Hub
      run: echo ${{ secrets.PASSWORD }} | docker login -u ${{ secrets.USERNAME }} --password-stdin
    - name: Push the image
      run: docker push yuvalost/dockerworkshop:${{ github.run_number }}
    - name: tag latest & push
      run: |
            docker push tag yuvalost/final-python:${{ github.run_number }} 
            docker push yuvalost/final-python:latest
